### ISSUE TITLE
go-filecoin show and go-filecoin chain should be combined

### ISSUE THREAD

**Issue by rosalinekarr** [filecoin-project/venus#1587]
### Description

The following commands have similar purposes but different and confusing names:

```
go-filecoin show block
go-filecoin chain ls
go-filecoin chain head
```

We should reduce them into the following commands and add support for verbose, human-readable output to all of them:

```
go-filecoin chain ls [optional cids for showing specific blocks]
go-filecoin chain head
```

### Acceptance criteria
- wiki must be updated to replace any instances of the old commands
- readme must be scrubbed for any instances of the old commands

**Comment by deaswang** [comment]
How about update like this:

`go-filecoin chain block [-m] <CID>`
because `show block` and `chain ls` call different Porcelain APIs, different logic process.

add optional `-b, --begin num` and `-e, --end num` to control the block height for `go-filecoin chain ls`, without end mean from head tipset, without begin mean to genesis.

**Comment by deaswang** [comment]
how to commit Wiki repo? how about submit one patch file at here?

**Comment by deaswang** [comment]
@mishmosh how is the proposal?

**Comment by deaswang** [comment]
here is WIki patch file
[0001-update-wiki-for-combine-chain-and-show-1587.zip](https://github.com/filecoin-project/go-filecoin/files/3421400/0001-update-wiki-for-combine-chain-and-show-1587.zip)

**Comment by eshon** [comment]
We were thinking of moving the go-filecoin wiki to [filecoin-project/docs/](https://github.com/filecoin-project/docs/tree/master/go-filecoin-tutorial) to enable community PRs but not sure if this has been discussed with the go-filecoin dev team yet.

Also this update would depend on merging the PR and adding it to a later release. We can apply the wiki patch later on if that happens.

**Comment by deaswang** [comment]
#3196 
Should this issue necessary now?
@rosalinekarr @mishmosh

**Comment by anorth** [comment]
Yes, this issue remains to clean up the organisation of the CLI actions, such that they read like `chain show`, `messages show` rather than `show block`. This will require moving much of that code around.

Maybe something like:
- `chain show [--full] <cid>...`: prints block headers / full blocks
- `chain ls`: prints block header cids for the whole chain
- `chain head`: prints head tipset CIDs

I don't think I've made a complete proposal - I haven't addresses messages/receipts.

Regarding your proposal for arguments, I think we should defer that to a separate PR from this reorganisation, but I like the idea in general.
