### ISSUE TITLE
improve error message when there is an insufficient gas limit

### ISSUE THREAD

**Issue by pooja** [filecoin-project/venus#1752]
### Description

When trying to run `go-filecoin miner create 10 100 --from=${MINER_OWNER_ADDR} --price=0 --limit=0`, I ran into this error message: `Error: Could not create miner. Please consult the documentation to setup your wallet and genesis block correctly: Error executing command. Consult the logs.`

The fix, as @ZenGround0 and @frrist were kind enough to inform me, was to up the gas limit. This command worked: `go-filecoin miner create 10 100 --from=${MINER_OWNER_ADDR} --price=0 --limit=300`

Can we please have a more descriptive error message that tells people to increase the gas limit when that is the cause of the error?

### Acceptance criteria

The error message tells the user to try increasing the gas limit to a minimum of 300

**Comment by mishmosh** [comment]
@mslipoer can you look into how much detail is in the error codes? If the error can be specifically traced to gas limit, could you change the error msg to something like this:

"Error: Could not create miner because gas limit too low. Please increase the gas limit and try again."

We should not hardcode a recommended gas limit.

**Comment by mslipper** [comment]
Got it, will do.

**Comment by gargdeepak** [comment]
if this is still an issue I can pick it up !

**Comment by anorth** [comment]
Thanks, go for it.
