### ISSUE TITLE
`propose-storage-deal` needs limit and price options

### ISSUE THREAD

**Issue by ognots** [filecoin-project/venus#1935]
### Description

`go-filecoin client propose-storage-deal` should allow setting limit and price options to keep consistency with similar commands

### Acceptance criteria

* when running `go-filecoin client propose-storage-deal --help` I should see `--limit` and `--price` options listed
* setting `--limit` and `--price` should set limit and price 😄 

### Risks + pitfalls

No obvious ones

### Where to begin

TBD

**Comment by ognots** [comment]
@anorth @acruikshank sorry, my brain wasn't working obviously. it's for `go-filecoin client propose-storage-deal`

**Comment by phritz** [comment]
still don't follow, @acruikshank can you explain?

**Comment by acruikshank** [comment]
@phritz Part of the process of proposing a storage deal is creating payments for the miner. This involves creating a payment channel on chain. Currently the message that creates the payment channel is created with a constant gas price and constant gas limit (this is in `storage/client.go`). The gas price and gas limit should really be command line options to behave like other messages.

Since this issue was written, we have renamed all the --price and --limit options to --gas-price and --gas-limit.

This work could potentially wait until Gas v2 work where we'll get the ability to set dynamic defaults for gas price and limit. This would partially alleviate the need for these options, but we're probably always going to want to permit price and lmit overrides, so there's nothing wrong with doing this work now.
