### ISSUE TITLE
Remove HTTP Support from Genesis File Downloading

### ISSUE THREAD

**Issue by rosalinekarr** [filecoin-project/venus#2378]
### Description

Currently, we allow both HTTP and HTTPS for downloading the genesis file on init. It's more secure to require HTTPS for this, however there may some issues with HTTPS for users in other countries.

### Acceptance criteria

Genesis file downloading no longer supports HTTP

### Risks + pitfalls

Setting up HTTPS servers for the genesis file can be significantly more difficult than HTTP servers due to certificate requirements.

### Where to begin

Around line 155 of `commands/init.go`

**Comment by travisperson** [comment]
> Setting up HTTPS servers for the genesis file can be significantly more difficult than HTTP servers due to certificate requirements.

We support this ourselves for the nightly (along with any recent deployments). The user devnet will get this support come the next update.

Example: https://genesis.nightly.kittyhawk.wtf/genesis.car

FAST does serve the genesis over an http server instead of doing local disk access. I'd be interested to hear suggestions on how to handle this for local development.

**Comment by anorth** [comment]
We should ask the question of why are we even fetching the genesis over HTTP/S at all? We have a chain sync protocol for fetching blocks - all a node should need is the CID of the genesis it expects. We could distribute this in a config file.
