### ISSUE TITLE
go-filecoin daemon should log info to stdout

### ISSUE THREAD

**Issue by rosalinekarr** [filecoin-project/venus#2586]
### Description

Currently, all logs from `go-filecoin daemon` go to stderr, and the only thing printed to stdout is an initial message with the node's current peer id. We should be using stdout for all non-error logging, and stderr should only be used for error logging.

This is specifically creating issues with testing in that we can't dump stderr to the console on test failures because stderr is too busy with extra info logs. If stderr were only used for error logs, we could just pipe stderr from all daemons to the console in testing.

### Acceptance criteria

Error logs go to stderr. All other logs go to stdout.

**Comment by gmasgras** [comment]
I agree that logging errors to stderr is a good idea. It would also help us more easily filter logs when searching in Kibana

**Comment by rosalinekarr** [comment]
@travisperson @frrist, opinions?

**Comment by travisperson** [comment]
I think we will need to cross post this over to the `go-log` and request feedback there. We may be able to update the interface to support defined outputs per log level which would enable directing error levels to stderr and other levels to stdout.

I believe the reason for everything going to stderr is largely due to a patterned established by the golang standard logger and it's just been carried up through the layers.

> That logger writes to standard error and prints the date and time of each logged message.

_https://golang.org/pkg/log/#pkg-overview_

We could define two loggers, one backed by stdout, another by stderr for error logs only. This would require no changes to go-log, but would limit us to only having this split output for logs we write ourselves.

##### With regard to FAST

> This is specifically creating issues with testing in that we can't dump stderr to the console on test failures because stderr is too busy with extra info logs. If stderr were only used for error logs, we could just pipe stderr from all daemons to the console in testing.

While this would be an easy thing to do, it wouldn't really solve the problem as any test running in parallel would intermix logs. We should attempt to use the `testing.T` to print out messages anyways so that they are kept within the context of the test. This probably won't be too hard either way so I guess it's beside the point and just an implementation detail.

We can enforce all tests to log with JSON, so picking out the errors is pretty easy as we have a `level` field we can filter over. One of the ideas for FAST was to provide an easy way to determine if errors were logged during the execution of a command, this was one intended idea for `StartLogCapture` as we can easily wrap it in a JSON decoder and filter for errors.

**Comment by frrist** [comment]
I think we should allow logging output to be configured based on service (e.g. chain, core, node) and level (i.e info, error). For example, as a user I should be able to configure all error leveled logs to be written to a file, or in the case of this issue, StdErr.

I think this is an issue with go-log -- might be worth pointing out in the design doc.

**Comment by rosalinekarr** [comment]
I added an issue to `ipfs/go-log`: https://github.com/ipfs/go-log/issues/60

@frrist, as for adding configuration and writing to files, I think we should stick to the [12factor guidelines on logs](https://12factor.net/logs) and just pipe out rather than trying to build a complex system around managing logs. If we need managed logs, we can pipe our output to existing log management software, like Logstash, Kibana or Papertrail.

Let's use pipes as they were meant to be used and leave log management to the log managers.

**Comment by frrist** [comment]
By output I mean an `io.writer`, this could be a file, a socket, or stderr. Logrus has a good example of this [here](https://github.com/sirupsen/logrus/blob/5bd5a315a50f7f5663063a3f608757fdca721f7f/exported.go#L19).

**Comment by rosalinekarr** [comment]
@frrist, yeah, I'm saying `go-filecoin` shouldn't have any concept of where its logs are going. It should just write to stdout and stderr, and we should use regular unix piping to direct those logs to some other application for managing logs. The only `io.Writer`s we should have for logging are `os.Stdout` and `os.Stderr`.
