### ISSUE TITLE
Daemon output on intial setup is unclear to new users

### ISSUE THREAD

**Issue by RobQuistNL** [filecoin-project/venus#2612]
### Description
When initially setting up a node for Filecoin, people will follow the [readme from the project](https://github.com/filecoin-project/go-filecoin/blob/master/README.md) and after installing will end up in the [Getting Started wiki](https://github.com/filecoin-project/go-filecoin/wiki/Getting-Started).

The setup is clear and easy to follow, but as soon as people start up the daemon, some messages come flying at the user which make the user doubt they've setup their node correctly.

3 of the major issues I've ran into:
#### Output of the daemon, before syncing, shows (a lot of) warning messages:
<details>
  <summary>Click to show one of the type of error messages</summary>

```
23:52:01.602 WARNI /fil/hello: genesis cid: zDPWYqFCutuHwRZhGXzji9L4eHeoFxxNCxCruGjWje36aAvbK2XV does not match: zDPWYqFCu9VdMN9pUSSttbjJsxd2sTJGZjXv8AGZvquxnsMRFh9e, disconnecting from peer: <peer.ID Qm*eVwka9> hello.go:93
```
</details>

#### Before really syncing, the daemon shows batches of "syncing the chain" messages which do not seem to represent the actual and current head of the chain:
<details>
  <summary>Click to show console output</summary>

```
23:51:56.554  INFO chain.sync: syncing the chain, currently at block height 46981 default_syncer.go:147
23:51:56.933  INFO chain.sync: syncing the chain, currently at block height 44456 default_syncer.go:147
23:51:57.230  INFO chain.sync: syncing the chain, currently at block height 42223 default_syncer.go:147
23:51:57.653  INFO chain.sync: syncing the chain, currently at block height 40206 default_syncer.go:147
23:51:57.972  INFO chain.sync: syncing the chain, currently at block height 38065 default_syncer.go:147
23:51:58.311  INFO chain.sync: syncing the chain, currently at block height 35454 default_syncer.go:147
23:51:58.669  INFO chain.sync: syncing the chain, currently at block height 33236 default_syncer.go:147
23:51:58.907  INFO chain.sync: syncing the chain, currently at block height 30253 default_syncer.go:147
23:51:59.381  INFO chain.sync: syncing the chain, currently at block height 26915 default_syncer.go:147
23:51:59.694  INFO chain.sync: syncing the chain, currently at block height 24823 default_syncer.go:147
23:52:00.247  INFO chain.sync: syncing the chain, currently at block height 22938 default_syncer.go:147
23:52:00.886  INFO chain.sync: syncing the chain, currently at block height 21435 default_syncer.go:147
23:52:01.497  INFO chain.sync: syncing the chain, currently at block height 19507 default_syncer.go:147
```
</details>
It seems to start over and over again, from high numbers to low numbers. This is very confusing.

#### After a while the chain will actually start syncing, and this takes a very long time (see issue #2050 )

When you're unfamiliar with the project the error messages throw you off, and the "chain sync" messages in reverse order don't help.

I'm proposing to either hide the unclear bits of the daemon output, or easier, change the wiki so that the daemon will be setup as a background service (possibly ran on boot as well?).

To get a sense of what the daemon is doing, and how long it takes, it would be nice to have some simple functions to read out the current state or see a time window. Maybe a simple command like `go-filecoin status` to show progress, or `go-filecoin monitor` as a continous stream of status information on sync state?

### Acceptance criteria
- Initial setup of the project raises less questions with new and unexperienced users.
- The wiki shows a way to set up the daemon as a background service, so the users won't be thrown off by valid (debug-ish) messages
- Some simple features in the CLI to get an easier overview of how far the chain sync / state is on this node

### Risks + pitfalls
- Less / harder to reach information if something really does go wrong in the daemon

### Where to begin
- Get the discussion started :) These are just my findings and I'm unfamiliar with the project or the code.

*Please note that this is my first issue and I'd love some feedback*

**Comment by ZenGround0** [comment]
This is a valuable set of information and suggestions.  Thank you for filing this.  We recognize that these issues badly need attention and REALLY want to get to them ASAP.  However please understand that we are aggressively prioritizing fundamentals at the expense of leaving UX fires burning.  It will likely be a while before a lot of this is addressed (particularly optimizing the chain processing).

**Comment by RobQuistNL** [comment]
Hey @ZenGround0, thanks for the quick reply! I've gotten very quick and nice responses from everyone on the Slack channels - basically stating the same. Completely fine and understandable that the UX is not something to focus on (I was actually surprised to see such detailed wiki's at this point of development :) ) and I hope I can help and contribute soon. 

Would reviewing pull requests regarding UX improvements be something you have the time for? Or would you prefer PR's regarding functionality and bugfixes?

**Comment by ZenGround0** [comment]
@RobQuistNL in general UX PRs are welcome.

At this stage in the project we haven't thought through any really solid process for planning new features in the open users.  The thing I would like to avoid is having you or other contributors put a lot of work into something that we end up never merging because it conflicts with other goals or constraints that you were not aware of at the start.

I think that something pretty lightweight will work for now.  Specifically if you are interested in taking on some of the work listed above the way to move forward is (1) file issues with narrower scope that will map 1-1 with a PR, (2) tag me and other people that seem relevant (looking at git blame for example) to the work suggested (3) hash out some design discussion in the issue and get an ack from one of the committers/maintainers that you are good to move ahead.  If you want to open a PR before reaching consensus in the issue that is fine, there is just a higher risk that your PR won't be merged or will be caught up in design discussion during the PR review.

Some of the work suggested above I can ack right now.  Changing the warnings about different genesis cids to debugs is a good idea.  Doing anything to improve the chain sync output is a good idea.

I am less certain about the background service work which should be evaluated in its own issue.  I like the idea of CLI utils exposing info to the user but want any work there to be coordinated with the expertise of committers who have done and are maybe planning work in similar areas (particularly @frrist and @travisperson).

Patches for speeding up the chain processing is probably best to defer for now as we don't want your work to collide with other ongoing work.  However if you are interested in profiling that code (`consensus/expected.go:RunStateTransition` is the right entry point) and reporting findings back in an issue, this would be valuable.
