### ISSUE TITLE
In Heartbeats Miner Address is often empty

### ISSUE THREAD

**Issue by eshon** [filecoin-project/venus#3056]
### Description

A Network Stats Dashboard suggestion from @travisperson was replacing Peer IDs with Miner Addresses in the [Miners Table](https://stats.kittyhawk.wtf/storage/mining) (and throughout the dashboard). However Miner Addresses are often empty, even if they have proven storage. They're [allowed to be empty in Heartbeats](https://github.com/filecoin-project/go-filecoin/blob/239bfc9367f9c2b42ec307c15ddbfe1393e01468/metrics/heartbeat.go#L45) but is there a way to make sure they are populated more often?

<img width="661" alt="Screen Shot 2019-07-11 at 6 06 37 PM" src="https://user-images.githubusercontent.com/1017762/61066915-ba11d280-a406-11e9-9137-347266ac28a0.png">

**Comment by travisperson** [comment]
The comment on that code I believe is just saying that not all nodes may have miners configured. As far as I can tell, if the node has a miner address set it will show up in the heartbeat.

I'm not sure how that snapshot of the dashboard is filling in that information. The dashboard must have access to the miner, otherwise there would be no way to get the storage or power. @mslipper can you provide some insight into what is happening?
