### ISSUE TITLE
Message waiter technical debt

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/venus#3194]
### Description
The message waiter is one of the thorniest, oldest and worst pieces of software in the node.  I feel ok saying this because I wrote it :)

There is some really ugly error swallowing going on inside of `receiptFromTipSet` that needs to be addressed.  The existing TODOs track some error swallowing that is based on complexity in node tests that very likely does not exist anymore

A separate but relevant piece of background is that the waiter actually runs the processor every time it finds a message.  It might make a lot of sense to extend the chain store's metadata to include the set of aggregate messages and receipts alongside the aggregate state of a tipset to avoid this processor dependency.

### Acceptance criteria
Fix up technical debt in TODOs

### Risks + pitfalls
Keep in mind the processor dependency potential refactors of the chain store that might make this go away.  That refactor would probably make the technical debt tracked in this issue disappear, so only assign this or work on it if that work seems deprioritized.

### Where to begin
Read `waitForMessage` and `receiptFromTipSet` carefully.

**Comment by travisperson** [comment]
Should `message wait` use the outbox as it's source of truth? The outbox already manages message life cycle by removing messages that are mined into blocks and messages that expire due to timeout. The fact that you can send a message and have it expire, while `message wait` hangs around I think is a bad design.

This also helps remove all the timeouts we have around `message wait` in the code, such as with our current deals protocol and payment channel creation.

https://github.com/filecoin-project/go-filecoin/blob/5427eb7a0cc9558e4c61eeeaab9cc58408fa8931/protocol/storage/client.go#L194

https://github.com/filecoin-project/go-filecoin/blob/5427eb7a0cc9558e4c61eeeaab9cc58408fa8931/porcelain/payments.go#L136

**Comment by anorth** [comment]
I don't think it should use the outbox. Waiting should work for any message, not just one generated locally. We can adjust the default message-wait timeout to match the outbox if that's a sensible default.

**Comment by travisperson** [comment]
Ah ya, completely forgot about external messages.
