### ISSUE TITLE
Fetch and validate headers before block bodies (aka GraphChainsync stage 3)

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/venus#3281]
### Description

Now that we've separated messages and receipts from block headers, we can potentially fetch headers first to verify you're on a valid chain that extends to the genesis block before fetching the remaining data in messages and receipts.

### Acceptance criteria

- Graphsync Fetcher first can make a query to get all the needed block headers 
- ChainSync verifies chain is valid
- Graphsync Fetcher makes a query to get all the missing messages and receipts -- it's not clear there's a way to do this without the remote resending the block headers, though presumably the block headers themselves are not that much data in comparison the to the messages themselves.

### Risks + pitfalls

-- not clear till we have user devnet running exactly how much network fetch time is a major slowdown at this point

### Where to begin

-- Define interfaces for fetcher to make queries with and without messages

**Comment by anorth** [comment]
I just want to point out that this is an important security property, not an optimisation. Since headers are fetched in descending height order before any of them can be validated (in ascending height order), an attacker generating a false chain can currently force nodes to expend lots of resources fetching and validating a false chain.

This change will greatly reduce the bandwidth and time required to fetch all the headers, which can be validated before fetching any of the block bodies. The bodies can then be fetched (and validated in parallel) in a more-or-less ascending height order.
