### ISSUE TITLE
Periodically Prune VM Storage

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/venus#3451]
### Description

VM Actors maintain an in memory storage cache that keeps live blocks that haven't been written to the block store yet. At the moment, this memory cache is seemingly never pruned, even for chunks that are no longer part of the active state tree.

The VM Storage class has a Prune method that removes chunks that are no longer part of the active live state tree from memory. It appears not to be called in the live code at all though.

### Acceptance criteria

Prune the VM storage to minimize memory performance.

### Risks + pitfalls

Over-pruning might possibly decrease performance by reading too often from disk?

### Where to begin

The first question is how often to prune. My initial read of the code suggests the Prune method simply removes chunks that are "dangling" -- i.e. not part of the live state tree for the actor. Given that, an easy place to do that in my head is StorageMap.Flush()

However, that seems like it might be too often, and perhaps we could use input from folks who've worked on this code more like @acruikshank

**Comment by anorth** [comment]
Recent historical state–that which was not dangling at some recent past tipset–is likely accessed during the churn that is the last few rounds in the chain until the re-orgs settle down. Pruning every time a tipset is accepted could be too frequent, incurring a bunch of disk reads immediately afterwards. 

A cache that is unbounded but can only be pruned in totality sounds like a poor design, but I am not intimately familiar with that area of the code. It's likely more complicated than "just a cache".

**Comment by acruikshank** [comment]
The cache is a temporary cache layer over persistent storage that is discarded after the state transition for a single tipset or after a single message execution depending on the context. The `Flush` method effectively prunes by saving only the live IDs to disk. 

The benefit of `Prune` is that it can reduce memory usage while the state transition is in progress. If it is called, it should probably be called just after `Commit`. We could also iterate the storage map and call it for all actors at message boundaries (this might be about the same thing). We definitely should do some analysis before using `Prune`, because it could easily degrade performance.
