### ISSUE TITLE
Enlarge the default maxNonceGap value 

### ISSUE THREAD

**Issue by steven004** [filecoin-project/venus#3487]
**Describe the bug**:
Currently, a miner's default configuration for messagePool is like: 
```
	"mpool": {
		"maxPoolSize": 10000,
		"maxNonceGap": "100"
	},
```
However, we do see genesis node has different defaults setting the maxNonceGap 10000.  
100 is a relatively small number for a real network. Since the gap will really limit a node to receive messages from any single node. I would suggest: 1) set the universal number for all nodes, which is not configurable; 2) set it larger, e.g. up to 10000. (this may request maxPoolSize larger too)

**Expected behavior**:
Allow more messages sent from one node in one block.

**Comment by anorth** [comment]
I can't see a way we could enforce nodes in the network all use the same value here. It's at a block producer's discretion how many messages from an individual actor they accept into a block. I expect miners to tune this value as expected profit dictates.

Since it's configurable, can you not just reconfigure your nodes to a larger value?

We nevertheless could set the default higher. 10000 seems very large, though. 

@whyrusleeping the `maxNonceGap` is the max difference between an actor nonce at the head state and the nonce in an inbound message, so in effect limits the number of messages per actor in the message pool. It's part of general anti-spam protections. Do you have any thoughts?
