### ISSUE TITLE
Encoder cannot handle map[string]x with non-UTF8 keys

### ISSUE THREAD

**Issue by anorth** [filecoin-project/venus#3757]
The encoding round-trip test contains the following disabled case:

```
map[string]uint64{string(vmaddr.TestAddress.Bytes()): 1, string(vmaddr.TestAddress2.Bytes()): 2}
```

The keys fail to decode, reporting "cbor: invalid UTF-8 string"

I don't think this is blocking anything immediate, because neither chain state nor the blockchain structures themselves will have any maps (map encoding has other issues like stable ordering, too).

FYI @ZenGround0 @icorderi

**Comment by ZenGround0** [comment]
Written elsewhere but putting here for persistence:

Since the go strings in question contain non-UTF8 characters I believe this error is expected.  Our cbor library tries to encode go strings as major type 3 but cannot because they are not UTF-8 which required by cbor spec.

Ideally we should investigate the above claim to make sure it really is an expected error (i.e. do other libs like refmt and cbg also fail here?) and if not we can file an issue in fxamacker cbor.
