### ISSUE TITLE
Resurrect seal-now and add-piece commands

### ISSUE THREAD

**Issue by anorth** [filecoin-project/venus#3865]
The seal-now command has been lost, and add-piece is not hooked up. Bring these back for manual mining operations via the storage mining module.

Note that it should be possible to seal an empty sector. The sectorbuilder's unsealed sector CID method will fill un-used space with zero sectors.

**Comment by anorth** [comment]
@acruikshank  Done?

**Comment by acruikshank** [comment]
The seal-now command that seals and commits and empty sector has been renamed pledge-sector and it is definitely done. 

We don't have add-piece (the command where a miner can store a piece within a sector that they then seal and commit). We do have propose-storage deal, which allows a client to make a deal with a miner to store a piece within a sector that the miner then seals and commits.

I believe (but haven't tested) a miner may be able to propose a deal with themselves with propose-deal, which would be add-piece with some unnecessary transfer of funds. The problem is that the miner will only accept a deal if it meets the ask price, and a miner probably wouldn't want to lower the ask price to do a self-deal, because it would risk automatically accepting other deals that are too cheap. 

There are probably some pretty cheap solutions now to get add-piece, but I don't know where it fits in priorities.
