### ISSUE TITLE
Don't expose miner's on chain state directly from state view

### ISSUE THREAD

**Issue by anorth** [filecoin-project/venus#4025]
The state view has exposed the miner.Info structure directly. This is contrary to the state view's explicit reason for existence, which is abstracting the concrete chain state representation so that it can be versioned through protocol upgrades without wreaking havoc on code that uses it.

Replace this with a private structure carrying only the necessary information, and divorced from chain state representation.

See also https://github.com/filecoin-project/storage-fsm/issues/13

**Comment by acruikshank** [comment]
I have concerns about this strategy for future-proofing the go-filecoin code against protocol upgrades. It's difficult to design an abstraction against unknown future changes. Increasing the granularity of access to the chain reduces the chances that code unrelated to the purpose of a protocol upgrade will need to be modified, but the fact that it is unrelated means that those modifications would be syntactic and trivial to correct.

My fear is that this abstraction is an, admittedly small, up-front cost with an unknown and possibly negative long-term payoff (negative if the abstraction is so off that it costs more to fix). As an example, we could continue to reduce access to the chain so that StateView callers only access primitives. A protocol change may require versioned structs, and it may be easier in the end for go-filecoin to deal with StateView responses by switching over struct types. There are still lots of ways the state view could abstract over this. In cases where go-filecoin code needs to respond to protocol changes, these abstractions will probably do more harm than good by creating a muddled view of the truth on chain.

Ultimately I agree that we're accumulating tech debt here, but I'm arguing it's debt with a negative interest rate.
