### ISSUE TITLE
RetrievalClientNodeConnector: Lane allocation should check lane limit

### ISSUE THREAD

**Issue by shannonwells** [filecoin-project/venus#4067]
**Describe the bug**:
Lane allocation does not check LaneLimit before adding a new lane to local (payment channel manager) store.  This is checked in specs-actors, however, lane allocation happens off chain unless there is a settle/collect event.

- Filecoin Version: master

**Comment by anorth** [comment]
@hannahhoward related to our conversation today, this kind of logic should be on the module side of the API, not on the node side replicated for each implementation.

**Comment by hannahhoward** [comment]
@anorth I agree in principle but I think I want to make a clear distinction between "module side" and "markets side"

Specifically, payment channels, while currently only used for retrieval, are to my understanding a general payment system that maybe used for any time of payment between parties. As such, to the extent this logic lives on the "module side" I think it lives in a shared payment channel manager module, which we are working on a proposal for.

I do not think the API for retrieval should change, or that a lane count check should live in the retrieval market.

**Comment by anorth** [comment]
Ok, I think at least a point of disagreement is clear. I think the API required by the retrieval module _should_ change so that wangling channels is done on the module side. Currently it is required that the node/connector provide very high level managed behaviour.

Yes a library of code for channel wrangling, used by the retrieval module, but usable by other modules, is a good idea. But I don't think the payment channel manager should live inside the node as it currently does. It should be owned by the markets module and utilize the same thin API to the node for state access as other modules do.

I am 70% confident in this view, not certain. It does depend on questions about effective state indexing, etc.

Payment channels are a general mechanism in one sense, but they are also a highly specific contract on an arbitrary state consensus system. When we have user-defined contracts there will be many different payment channel implementations. Our markets module may require use of a specific one (tho that is likely to change too), but a Filecoin node should probably not have loads of dedicated logic about these "application" specifics.

**Comment by hannahhoward** [comment]
We should talk high bandwidth, but FWIW, I think there is less disagreement than you think. I am in agreement that payment channel manager living outside the node, assuming LOTUS is on board. cc: @whyrusleeping
