### ISSUE TITLE
[STM] Start annotations on `venus-messager`

### ISSUE THREAD

**Issue by Fatman13** [filecoin-project/venus#5273]

**Comment by zl03jsj** [comment]
Since the `GasEstimateMessageGas` of `messageSelector` is deprecated, and would be removed  soon.
https://github.com/filecoin-project/venus-messager/blob/632f7b8e48049dbbfe4ca7235975f7f87ef62721/service/message_selector.go#L350-L380

There is no necessary to keep its catalogs in STM now:
https://github.com/filecoin-project/system-test-matrix/blob/cd7e06431903b3892b693db68a51ca03c493ea79/frontend/apps/web/scripts/data/systems/venus-messenger/message_selector.yml#L13-L33

@bokimilinkovic @StefanGajic
